In [62]:
import numpy as np
import pandas as pd
import plotly.express as px

In [63]:
#Import the data 
ins=pd.read_csv('insurance_claims (1).csv')
ins.head()

,years_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported
0,27.3,48,521585,10/17/2014,OH,250/500,1000,1406.91,0,466132,...,2,YES,71610,6510,13020,52080,Saab,92x,2004,Y
1,19.0,42,342868,6/27/2006,IN,250/500,2000,1197.22,5000000,468176,...,0,?,5070,780,780,3510,Mercedes,E400,2007,Y
2,11.2,29,687698,9/6/2000,OH,100/300,2000,1413.14,5000000,430632,...,3,NO,34650,7700,3850,23100,Dodge,RAM,2007,N
3,21.3,41,227811,5/25/1990,IL,250/500,2000,1415.74,6000000,608117,...,2,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y
4,19.0,44,367455,6/6/2014,IL,500/1000,1000,1583.91,6000000,610706,...,1,NO,6500,1300,650,4550,Accura,RSX,2009,N

In [64]:
ins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 39 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   years_as_customer            1000 non-null   float64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   object
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      1000 non-null   object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              1000 non-null   object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   object
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        1000 non-null   object
 22  incident_state               1000 non-null   object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
dtypes: float64(2), int64(16), object(21)
memory usage: 304.8+ KB

In [65]:
ins.describe()

,years_as_customer,age,policy_number,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,capital-gains,capital-loss,incident_hour_of_the_day,number_of_vehicles_involved,bodily_injuries,witnesses,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_year
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000
mean,17.005400,38.948000,546238.648000,1136.000000,1256.406150,1.101000e+06,501214.488000,25126.100000,-26793.700000,11.644000,1.83900,0.992000,1.487000,52761.94000,7433.420000,7399.570000,37928.950000,2005.103000
std,9.593114,9.140287,257063.005276,611.864673,244.167395,2.297407e+06,71701.610941,27872.187708,28104.096686,6.951373,1.01888,0.820127,1.111335,26401.53319,4880.951853,4824.726179,18886.252893,6.015861
min,0.000000,19.000000,100804.000000,500.000000,433.330000,-1.000000e+06,430104.000000,0.000000,-111100.000000,0.000000,1.00000,0.000000,0.000000,100.00000,0.000000,0.000000,70.000000,1995.000000
25%,9.675000,32.000000,335980.250000,500.000000,1089.607500,0.000000e+00,448404.500000,0.000000,-51500.000000,6.000000,1.00000,0.000000,1.000000,41812.50000,4295.000000,4445.000000,30292.500000,2000.000000
50%,16.650000,38.000000,533135.000000,1000.000000,1257.200000,0.000000e+00,466445.500000,0.000000,-23250.000000,12.000000,1.00000,1.000000,1.000000,58055.00000,6775.000000,6750.000000,42100.000000,2005.000000
75%,23.025000,44.000000,759099.750000,2000.000000,1415.695000,0.000000e+00,603251.000000,51025.000000,0.000000,17.000000,3.00000,2.000000,2.000000,70592.50000,11305.000000,10885.000000,50822.500000,2010.000000
max,39.900000,64.000000,999435.000000,2000.000000,2047.590000,1.000000e+07,620962.000000,100500.000000,0.000000,23.000000,4.00000,2.000000,3.000000,114920.00000,21450.000000,23670.000000,79560.000000,2015.000000

In [66]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
ins['fraud_reported']=le.fit_transform(ins['fraud_reported'])
ins['fraud_reported'].value_counts()


ins['insured_sex']=le.fit_transform(ins['insured_sex'])

In [67]:
ins.head()

,years_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported
0,27.3,48,521585,10/17/2014,OH,250/500,1000,1406.91,0,466132,...,2,YES,71610,6510,13020,52080,Saab,92x,2004,1
1,19.0,42,342868,6/27/2006,IN,250/500,2000,1197.22,5000000,468176,...,0,?,5070,780,780,3510,Mercedes,E400,2007,1
2,11.2,29,687698,9/6/2000,OH,100/300,2000,1413.14,5000000,430632,...,3,NO,34650,7700,3850,23100,Dodge,RAM,2007,0
3,21.3,41,227811,5/25/1990,IL,250/500,2000,1415.74,6000000,608117,...,2,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,1
4,19.0,44,367455,6/6/2014,IL,500/1000,1000,1583.91,6000000,610706,...,1,NO,6500,1300,650,4550,Accura,RSX,2009,0

In [68]:
ins.columns

Index(['years_as_customer', 'age', 'policy_number', 'policy_bind_date',
       'policy_state', 'policy_csl', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'capital-gains', 'capital-loss',
       'incident_date', 'incident_type', 'collision_type', 'incident_severity',
       'authorities_contacted', 'incident_state', 'incident_city',
       'incident_location', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'property_damage', 'bodily_injuries',
       'witnesses', 'police_report_available', 'total_claim_amount',
       'injury_claim', 'property_claim', 'vehicle_claim', 'auto_make',
       'auto_model', 'auto_year', 'fraud_reported'],
      dtype='object')

In [69]:
ins.drop(['auto_model','insured_zip','policy_number','policy_bind_date','incident_hour_of_the_day','total_claim_amount',
         'incident_location','policy_state','policy_csl'],axis=1,inplace=True)
ins.columns

Index(['years_as_customer', 'age', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'capital-gains', 'capital-loss',
       'incident_date', 'incident_type', 'collision_type', 'incident_severity',
       'authorities_contacted', 'incident_state', 'incident_city',
       'number_of_vehicles_involved', 'property_damage', 'bodily_injuries',
       'witnesses', 'police_report_available', 'injury_claim',
       'property_claim', 'vehicle_claim', 'auto_make', 'auto_year',
       'fraud_reported'],
      dtype='object')

In [70]:
ins.corr()

C:\Users\HP\AppData\Local\Temp\ipykernel_18168\1958209643.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  ins.corr()

,years_as_customer,age,policy_deductable,policy_annual_premium,umbrella_limit,insured_sex,capital-gains,capital-loss,number_of_vehicles_involved,bodily_injuries,witnesses,injury_claim,property_claim,vehicle_claim,auto_year,fraud_reported
years_as_customer,1.000000,0.922147,0.026709,0.004963,0.015522,0.060887,0.006253,0.020241,0.014652,-0.010084,0.058295,0.065347,0.034967,0.061115,-0.000150,0.020499
age,0.922147,1.000000,0.029188,0.014404,0.018126,0.073337,-0.007075,0.007368,0.022102,-0.015679,0.052359,0.075522,0.060898,0.062588,0.001354,0.012143
policy_deductable,0.026709,0.029188,1.000000,-0.003245,0.010870,-0.009733,0.035212,-0.023544,0.051214,-0.022765,0.066639,0.039107,0.064792,0.005269,0.026105,0.014817
policy_annual_premium,0.004963,0.014404,-0.003245,1.000000,-0.006247,0.038853,-0.013738,0.023547,-0.045991,0.026780,0.002332,-0.017633,-0.011654,0.020246,-0.049226,-0.014480
umbrella_limit,0.015522,0.018126,0.010870,-0.006247,1.000000,0.010688,-0.047268,-0.024056,-0.021270,0.022743,-0.006738,-0.045412,-0.023790,-0.038584,0.009893,0.058622
insured_sex,0.060887,0.073337,-0.009733,0.038853,0.010688,1.000000,-0.020494,-0.021705,0.018793,-0.020297,0.042463,0.000924,-0.014868,-0.029609,-0.028247,0.030873
capital-gains,0.006253,-0.007075,0.035212,-0.013738,-0.047268,-0.020494,1.000000,-0.046904,0.061643,0.055829,-0.017651,0.025934,-0.000779,0.015836,0.031398,-0.019173
capital-loss,0.020241,0.007368,-0.023544,0.023547,-0.024056,-0.021705,-0.046904,1.000000,-0.014895,-0.024418,-0.041330,-0.046060,-0.022863,-0.032665,-0.056615,-0.014863
number_of_vehicles_involved,0.014652,0.022102,0.051214,-0.045991,-0.021270,0.018793,0.061643,-0.014895,1.000000,0.014030,-0.014669,0.224650,0.219084,0.269393,0.034554,0.051839
bodily_injuries,-0.010084,-0.015679,-0.022765,0.026780,0.022743,-0.020297,0.055829,-0.024418,0.014030,1.000000,-0.005606,0.047319,0.039749,0.043449,-0.020527,0.033877
witnesses,0.058295,0.052359,0.066639,0.002332,-0.006738,0.042463,-0.017651,-0.041330,-0.014669,-0.005606,1.000000,-0.024843,0.052640,-0.022564,0.045791,0.049497
injury_claim,0.065347,0.075522,0.039107,-0.017633,-0.045412,0.000924,0.025934,-0.046060,0.224650,0.047319,-0.024843,1.000000,0.563866,0.722878,-0.013718,0.090975
property_claim,0.034967,0.060898,0.064792,-0.011654,-0.023790,-0.014868,-0.000779,-0.022863,0.219084,0.039749,0.052640,0.563866,1.000000,0.732090,-0.014508,0.137835
vehicle_claim,0.061115,0.062588,0.005269,0.020246,-0.038584,-0.029609,0.015836,-0.032665,0.269393,0.043449,-0.022564,0.722878,0.732090,1.000000,-0.042768,0.170049
auto_year,-0.000150,0.001354,0.026105,-0.049226,0.009893,-0.028247,0.031398,-0.056615,0.034554,-0.020527,0.045791,-0.013718,-0.014508,-0.042768,1.000000,0.007928
fraud_reported,0.020499,0.012143,0.014817,-0.014480,0.058622,0.030873,-0.019173,-0.014863,0.051839,0.033877,0.049497,0.090975,0.137835,0.170049,0.007928,1.000000